[build-system]
requires = [
    "setuptools>=38.6.0",
    "wheel>=0.31.0",
    "twine>=1.11.0"
]
build-backend = "ppbt.build"
backend-path = ["src"]

[tool.pytest.ini_options]
pythonpath = [
  "src"
]
